// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: base/v1/boards.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BoardsService_CreateBoard_FullMethodName = "/taskboard.v1.BoardsService/CreateBoard"
	BoardsService_GetBoard_FullMethodName    = "/taskboard.v1.BoardsService/GetBoard"
	BoardsService_ListBoards_FullMethodName  = "/taskboard.v1.BoardsService/ListBoards"
	BoardsService_UpdateBoard_FullMethodName = "/taskboard.v1.BoardsService/UpdateBoard"
	BoardsService_DeleteBoard_FullMethodName = "/taskboard.v1.BoardsService/DeleteBoard"
)

// BoardsServiceClient is the client API for BoardsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BoardsServiceClient interface {
	CreateBoard(ctx context.Context, in *CreateBoardRequest, opts ...grpc.CallOption) (*CreateBoardResponse, error)
	GetBoard(ctx context.Context, in *GetBoardRequest, opts ...grpc.CallOption) (*GetBoardResponse, error)
	ListBoards(ctx context.Context, in *ListBoardsRequest, opts ...grpc.CallOption) (*ListBoardsResponse, error)
	UpdateBoard(ctx context.Context, in *UpdateBoardRequest, opts ...grpc.CallOption) (*UpdateBoardResponse, error)
	DeleteBoard(ctx context.Context, in *DeleteBoardRequest, opts ...grpc.CallOption) (*DeleteBoardResponse, error)
}

type boardsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBoardsServiceClient(cc grpc.ClientConnInterface) BoardsServiceClient {
	return &boardsServiceClient{cc}
}

func (c *boardsServiceClient) CreateBoard(ctx context.Context, in *CreateBoardRequest, opts ...grpc.CallOption) (*CreateBoardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBoardResponse)
	err := c.cc.Invoke(ctx, BoardsService_CreateBoard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boardsServiceClient) GetBoard(ctx context.Context, in *GetBoardRequest, opts ...grpc.CallOption) (*GetBoardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBoardResponse)
	err := c.cc.Invoke(ctx, BoardsService_GetBoard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boardsServiceClient) ListBoards(ctx context.Context, in *ListBoardsRequest, opts ...grpc.CallOption) (*ListBoardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBoardsResponse)
	err := c.cc.Invoke(ctx, BoardsService_ListBoards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boardsServiceClient) UpdateBoard(ctx context.Context, in *UpdateBoardRequest, opts ...grpc.CallOption) (*UpdateBoardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBoardResponse)
	err := c.cc.Invoke(ctx, BoardsService_UpdateBoard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boardsServiceClient) DeleteBoard(ctx context.Context, in *DeleteBoardRequest, opts ...grpc.CallOption) (*DeleteBoardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBoardResponse)
	err := c.cc.Invoke(ctx, BoardsService_DeleteBoard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BoardsServiceServer is the server API for BoardsService service.
// All implementations must embed UnimplementedBoardsServiceServer
// for forward compatibility.
type BoardsServiceServer interface {
	CreateBoard(context.Context, *CreateBoardRequest) (*CreateBoardResponse, error)
	GetBoard(context.Context, *GetBoardRequest) (*GetBoardResponse, error)
	ListBoards(context.Context, *ListBoardsRequest) (*ListBoardsResponse, error)
	UpdateBoard(context.Context, *UpdateBoardRequest) (*UpdateBoardResponse, error)
	DeleteBoard(context.Context, *DeleteBoardRequest) (*DeleteBoardResponse, error)
	mustEmbedUnimplementedBoardsServiceServer()
}

// UnimplementedBoardsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBoardsServiceServer struct{}

func (UnimplementedBoardsServiceServer) CreateBoard(context.Context, *CreateBoardRequest) (*CreateBoardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBoard not implemented")
}
func (UnimplementedBoardsServiceServer) GetBoard(context.Context, *GetBoardRequest) (*GetBoardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBoard not implemented")
}
func (UnimplementedBoardsServiceServer) ListBoards(context.Context, *ListBoardsRequest) (*ListBoardsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBoards not implemented")
}
func (UnimplementedBoardsServiceServer) UpdateBoard(context.Context, *UpdateBoardRequest) (*UpdateBoardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBoard not implemented")
}
func (UnimplementedBoardsServiceServer) DeleteBoard(context.Context, *DeleteBoardRequest) (*DeleteBoardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBoard not implemented")
}
func (UnimplementedBoardsServiceServer) mustEmbedUnimplementedBoardsServiceServer() {}
func (UnimplementedBoardsServiceServer) testEmbeddedByValue()                       {}

// UnsafeBoardsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BoardsServiceServer will
// result in compilation errors.
type UnsafeBoardsServiceServer interface {
	mustEmbedUnimplementedBoardsServiceServer()
}

func RegisterBoardsServiceServer(s grpc.ServiceRegistrar, srv BoardsServiceServer) {
	// If the following call panics, it indicates UnimplementedBoardsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BoardsService_ServiceDesc, srv)
}

func _BoardsService_CreateBoard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBoardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoardsServiceServer).CreateBoard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoardsService_CreateBoard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoardsServiceServer).CreateBoard(ctx, req.(*CreateBoardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoardsService_GetBoard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBoardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoardsServiceServer).GetBoard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoardsService_GetBoard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoardsServiceServer).GetBoard(ctx, req.(*GetBoardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoardsService_ListBoards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBoardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoardsServiceServer).ListBoards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoardsService_ListBoards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoardsServiceServer).ListBoards(ctx, req.(*ListBoardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoardsService_UpdateBoard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBoardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoardsServiceServer).UpdateBoard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoardsService_UpdateBoard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoardsServiceServer).UpdateBoard(ctx, req.(*UpdateBoardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoardsService_DeleteBoard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBoardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoardsServiceServer).DeleteBoard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoardsService_DeleteBoard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoardsServiceServer).DeleteBoard(ctx, req.(*DeleteBoardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BoardsService_ServiceDesc is the grpc.ServiceDesc for BoardsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BoardsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "taskboard.v1.BoardsService",
	HandlerType: (*BoardsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBoard",
			Handler:    _BoardsService_CreateBoard_Handler,
		},
		{
			MethodName: "GetBoard",
			Handler:    _BoardsService_GetBoard_Handler,
		},
		{
			MethodName: "ListBoards",
			Handler:    _BoardsService_ListBoards_Handler,
		},
		{
			MethodName: "UpdateBoard",
			Handler:    _BoardsService_UpdateBoard_Handler,
		},
		{
			MethodName: "DeleteBoard",
			Handler:    _BoardsService_DeleteBoard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "base/v1/boards.proto",
}
