// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: base/v1/boards.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Board struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Board) Reset() {
	*x = Board{}
	mi := &file_base_v1_boards_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Board) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board) ProtoMessage() {}

func (x *Board) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_boards_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Board.ProtoReflect.Descriptor instead.
func (*Board) Descriptor() ([]byte, []int) {
	return file_base_v1_boards_proto_rawDescGZIP(), []int{0}
}

func (x *Board) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Board) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Board) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Board) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseRequest           `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBoardRequest) Reset() {
	*x = CreateBoardRequest{}
	mi := &file_base_v1_boards_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBoardRequest) ProtoMessage() {}

func (x *CreateBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_boards_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBoardRequest.ProtoReflect.Descriptor instead.
func (*CreateBoardRequest) Descriptor() ([]byte, []int) {
	return file_base_v1_boards_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBoardRequest) GetBase() *BaseRequest {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *CreateBoardRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateBoardRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateBoardRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateBoardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Board         *Board                 `protobuf:"bytes,2,opt,name=board,proto3" json:"board,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBoardResponse) Reset() {
	*x = CreateBoardResponse{}
	mi := &file_base_v1_boards_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBoardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBoardResponse) ProtoMessage() {}

func (x *CreateBoardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_boards_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBoardResponse.ProtoReflect.Descriptor instead.
func (*CreateBoardResponse) Descriptor() ([]byte, []int) {
	return file_base_v1_boards_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBoardResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *CreateBoardResponse) GetBoard() *Board {
	if x != nil {
		return x.Board
	}
	return nil
}

type GetBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseRequest           `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	BoardId       string                 `protobuf:"bytes,2,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoardRequest) Reset() {
	*x = GetBoardRequest{}
	mi := &file_base_v1_boards_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardRequest) ProtoMessage() {}

func (x *GetBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_boards_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardRequest.ProtoReflect.Descriptor instead.
func (*GetBoardRequest) Descriptor() ([]byte, []int) {
	return file_base_v1_boards_proto_rawDescGZIP(), []int{3}
}

func (x *GetBoardRequest) GetBase() *BaseRequest {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetBoardRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

type GetBoardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Board         *Board                 `protobuf:"bytes,2,opt,name=board,proto3" json:"board,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoardResponse) Reset() {
	*x = GetBoardResponse{}
	mi := &file_base_v1_boards_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardResponse) ProtoMessage() {}

func (x *GetBoardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_boards_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardResponse.ProtoReflect.Descriptor instead.
func (*GetBoardResponse) Descriptor() ([]byte, []int) {
	return file_base_v1_boards_proto_rawDescGZIP(), []int{4}
}

func (x *GetBoardResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetBoardResponse) GetBoard() *Board {
	if x != nil {
		return x.Board
	}
	return nil
}

type ListBoardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseRequest           `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBoardsRequest) Reset() {
	*x = ListBoardsRequest{}
	mi := &file_base_v1_boards_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBoardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBoardsRequest) ProtoMessage() {}

func (x *ListBoardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_boards_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBoardsRequest.ProtoReflect.Descriptor instead.
func (*ListBoardsRequest) Descriptor() ([]byte, []int) {
	return file_base_v1_boards_proto_rawDescGZIP(), []int{5}
}

func (x *ListBoardsRequest) GetBase() *BaseRequest {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ListBoardsRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type ListBoardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Boards        []*Board               `protobuf:"bytes,2,rep,name=boards,proto3" json:"boards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBoardsResponse) Reset() {
	*x = ListBoardsResponse{}
	mi := &file_base_v1_boards_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBoardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBoardsResponse) ProtoMessage() {}

func (x *ListBoardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_boards_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBoardsResponse.ProtoReflect.Descriptor instead.
func (*ListBoardsResponse) Descriptor() ([]byte, []int) {
	return file_base_v1_boards_proto_rawDescGZIP(), []int{6}
}

func (x *ListBoardsResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ListBoardsResponse) GetBoards() []*Board {
	if x != nil {
		return x.Boards
	}
	return nil
}

type UpdateBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseRequest           `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	BoardId       string                 `protobuf:"bytes,2,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBoardRequest) Reset() {
	*x = UpdateBoardRequest{}
	mi := &file_base_v1_boards_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBoardRequest) ProtoMessage() {}

func (x *UpdateBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_boards_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBoardRequest.ProtoReflect.Descriptor instead.
func (*UpdateBoardRequest) Descriptor() ([]byte, []int) {
	return file_base_v1_boards_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateBoardRequest) GetBase() *BaseRequest {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *UpdateBoardRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *UpdateBoardRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *UpdateBoardRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateBoardRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateBoardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Board         *Board                 `protobuf:"bytes,2,opt,name=board,proto3" json:"board,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBoardResponse) Reset() {
	*x = UpdateBoardResponse{}
	mi := &file_base_v1_boards_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBoardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBoardResponse) ProtoMessage() {}

func (x *UpdateBoardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_boards_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBoardResponse.ProtoReflect.Descriptor instead.
func (*UpdateBoardResponse) Descriptor() ([]byte, []int) {
	return file_base_v1_boards_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateBoardResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *UpdateBoardResponse) GetBoard() *Board {
	if x != nil {
		return x.Board
	}
	return nil
}

type DeleteBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseRequest           `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	BoardId       string                 `protobuf:"bytes,2,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBoardRequest) Reset() {
	*x = DeleteBoardRequest{}
	mi := &file_base_v1_boards_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBoardRequest) ProtoMessage() {}

func (x *DeleteBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_boards_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBoardRequest.ProtoReflect.Descriptor instead.
func (*DeleteBoardRequest) Descriptor() ([]byte, []int) {
	return file_base_v1_boards_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteBoardRequest) GetBase() *BaseRequest {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *DeleteBoardRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

type DeleteBoardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBoardResponse) Reset() {
	*x = DeleteBoardResponse{}
	mi := &file_base_v1_boards_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBoardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBoardResponse) ProtoMessage() {}

func (x *DeleteBoardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_boards_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBoardResponse.ProtoReflect.Descriptor instead.
func (*DeleteBoardResponse) Descriptor() ([]byte, []int) {
	return file_base_v1_boards_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteBoardResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

var File_base_v1_boards_proto protoreflect.FileDescriptor

const file_base_v1_boards_proto_rawDesc = "" +
	"\n" +
	"\x14base/v1/boards.proto\x12\ftaskboard.v1\x1a\x14base/v1/common.proto\"j\n" +
	"\x05Board\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\x96\x01\n" +
	"\x12CreateBoardRequest\x12-\n" +
	"\x04base\x18\x01 \x01(\v2\x19.taskboard.v1.BaseRequestR\x04base\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"p\n" +
	"\x13CreateBoardResponse\x12.\n" +
	"\x04base\x18\x01 \x01(\v2\x1a.taskboard.v1.BaseResponseR\x04base\x12)\n" +
	"\x05board\x18\x02 \x01(\v2\x13.taskboard.v1.BoardR\x05board\"[\n" +
	"\x0fGetBoardRequest\x12-\n" +
	"\x04base\x18\x01 \x01(\v2\x19.taskboard.v1.BaseRequestR\x04base\x12\x19\n" +
	"\bboard_id\x18\x02 \x01(\tR\aboardId\"m\n" +
	"\x10GetBoardResponse\x12.\n" +
	"\x04base\x18\x01 \x01(\v2\x1a.taskboard.v1.BaseResponseR\x04base\x12)\n" +
	"\x05board\x18\x02 \x01(\v2\x13.taskboard.v1.BoardR\x05board\"]\n" +
	"\x11ListBoardsRequest\x12-\n" +
	"\x04base\x18\x01 \x01(\v2\x19.taskboard.v1.BaseRequestR\x04base\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\"q\n" +
	"\x12ListBoardsResponse\x12.\n" +
	"\x04base\x18\x01 \x01(\v2\x1a.taskboard.v1.BaseResponseR\x04base\x12+\n" +
	"\x06boards\x18\x02 \x03(\v2\x13.taskboard.v1.BoardR\x06boards\"\xb1\x01\n" +
	"\x12UpdateBoardRequest\x12-\n" +
	"\x04base\x18\x01 \x01(\v2\x19.taskboard.v1.BaseRequestR\x04base\x12\x19\n" +
	"\bboard_id\x18\x02 \x01(\tR\aboardId\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"p\n" +
	"\x13UpdateBoardResponse\x12.\n" +
	"\x04base\x18\x01 \x01(\v2\x1a.taskboard.v1.BaseResponseR\x04base\x12)\n" +
	"\x05board\x18\x02 \x01(\v2\x13.taskboard.v1.BoardR\x05board\"^\n" +
	"\x12DeleteBoardRequest\x12-\n" +
	"\x04base\x18\x01 \x01(\v2\x19.taskboard.v1.BaseRequestR\x04base\x12\x19\n" +
	"\bboard_id\x18\x02 \x01(\tR\aboardId\"E\n" +
	"\x13DeleteBoardResponse\x12.\n" +
	"\x04base\x18\x01 \x01(\v2\x1a.taskboard.v1.BaseResponseR\x04base2\xa7\x03\n" +
	"\rBoardsService\x12R\n" +
	"\vCreateBoard\x12 .taskboard.v1.CreateBoardRequest\x1a!.taskboard.v1.CreateBoardResponse\x12I\n" +
	"\bGetBoard\x12\x1d.taskboard.v1.GetBoardRequest\x1a\x1e.taskboard.v1.GetBoardResponse\x12O\n" +
	"\n" +
	"ListBoards\x12\x1f.taskboard.v1.ListBoardsRequest\x1a .taskboard.v1.ListBoardsResponse\x12R\n" +
	"\vUpdateBoard\x12 .taskboard.v1.UpdateBoardRequest\x1a!.taskboard.v1.UpdateBoardResponse\x12R\n" +
	"\vDeleteBoard\x12 .taskboard.v1.DeleteBoardRequest\x1a!.taskboard.v1.DeleteBoardResponseB7Z5github.com/smarrog/task-board/shared/proto/base/v1;v1b\x06proto3"

var (
	file_base_v1_boards_proto_rawDescOnce sync.Once
	file_base_v1_boards_proto_rawDescData []byte
)

func file_base_v1_boards_proto_rawDescGZIP() []byte {
	file_base_v1_boards_proto_rawDescOnce.Do(func() {
		file_base_v1_boards_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_base_v1_boards_proto_rawDesc), len(file_base_v1_boards_proto_rawDesc)))
	})
	return file_base_v1_boards_proto_rawDescData
}

var file_base_v1_boards_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_base_v1_boards_proto_goTypes = []any{
	(*Board)(nil),               // 0: taskboard.v1.Board
	(*CreateBoardRequest)(nil),  // 1: taskboard.v1.CreateBoardRequest
	(*CreateBoardResponse)(nil), // 2: taskboard.v1.CreateBoardResponse
	(*GetBoardRequest)(nil),     // 3: taskboard.v1.GetBoardRequest
	(*GetBoardResponse)(nil),    // 4: taskboard.v1.GetBoardResponse
	(*ListBoardsRequest)(nil),   // 5: taskboard.v1.ListBoardsRequest
	(*ListBoardsResponse)(nil),  // 6: taskboard.v1.ListBoardsResponse
	(*UpdateBoardRequest)(nil),  // 7: taskboard.v1.UpdateBoardRequest
	(*UpdateBoardResponse)(nil), // 8: taskboard.v1.UpdateBoardResponse
	(*DeleteBoardRequest)(nil),  // 9: taskboard.v1.DeleteBoardRequest
	(*DeleteBoardResponse)(nil), // 10: taskboard.v1.DeleteBoardResponse
	(*BaseRequest)(nil),         // 11: taskboard.v1.BaseRequest
	(*BaseResponse)(nil),        // 12: taskboard.v1.BaseResponse
}
var file_base_v1_boards_proto_depIdxs = []int32{
	11, // 0: taskboard.v1.CreateBoardRequest.base:type_name -> taskboard.v1.BaseRequest
	12, // 1: taskboard.v1.CreateBoardResponse.base:type_name -> taskboard.v1.BaseResponse
	0,  // 2: taskboard.v1.CreateBoardResponse.board:type_name -> taskboard.v1.Board
	11, // 3: taskboard.v1.GetBoardRequest.base:type_name -> taskboard.v1.BaseRequest
	12, // 4: taskboard.v1.GetBoardResponse.base:type_name -> taskboard.v1.BaseResponse
	0,  // 5: taskboard.v1.GetBoardResponse.board:type_name -> taskboard.v1.Board
	11, // 6: taskboard.v1.ListBoardsRequest.base:type_name -> taskboard.v1.BaseRequest
	12, // 7: taskboard.v1.ListBoardsResponse.base:type_name -> taskboard.v1.BaseResponse
	0,  // 8: taskboard.v1.ListBoardsResponse.boards:type_name -> taskboard.v1.Board
	11, // 9: taskboard.v1.UpdateBoardRequest.base:type_name -> taskboard.v1.BaseRequest
	12, // 10: taskboard.v1.UpdateBoardResponse.base:type_name -> taskboard.v1.BaseResponse
	0,  // 11: taskboard.v1.UpdateBoardResponse.board:type_name -> taskboard.v1.Board
	11, // 12: taskboard.v1.DeleteBoardRequest.base:type_name -> taskboard.v1.BaseRequest
	12, // 13: taskboard.v1.DeleteBoardResponse.base:type_name -> taskboard.v1.BaseResponse
	1,  // 14: taskboard.v1.BoardsService.CreateBoard:input_type -> taskboard.v1.CreateBoardRequest
	3,  // 15: taskboard.v1.BoardsService.GetBoard:input_type -> taskboard.v1.GetBoardRequest
	5,  // 16: taskboard.v1.BoardsService.ListBoards:input_type -> taskboard.v1.ListBoardsRequest
	7,  // 17: taskboard.v1.BoardsService.UpdateBoard:input_type -> taskboard.v1.UpdateBoardRequest
	9,  // 18: taskboard.v1.BoardsService.DeleteBoard:input_type -> taskboard.v1.DeleteBoardRequest
	2,  // 19: taskboard.v1.BoardsService.CreateBoard:output_type -> taskboard.v1.CreateBoardResponse
	4,  // 20: taskboard.v1.BoardsService.GetBoard:output_type -> taskboard.v1.GetBoardResponse
	6,  // 21: taskboard.v1.BoardsService.ListBoards:output_type -> taskboard.v1.ListBoardsResponse
	8,  // 22: taskboard.v1.BoardsService.UpdateBoard:output_type -> taskboard.v1.UpdateBoardResponse
	10, // 23: taskboard.v1.BoardsService.DeleteBoard:output_type -> taskboard.v1.DeleteBoardResponse
	19, // [19:24] is the sub-list for method output_type
	14, // [14:19] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_base_v1_boards_proto_init() }
func file_base_v1_boards_proto_init() {
	if File_base_v1_boards_proto != nil {
		return
	}
	file_base_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_base_v1_boards_proto_rawDesc), len(file_base_v1_boards_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_base_v1_boards_proto_goTypes,
		DependencyIndexes: file_base_v1_boards_proto_depIdxs,
		MessageInfos:      file_base_v1_boards_proto_msgTypes,
	}.Build()
	File_base_v1_boards_proto = out.File
	file_base_v1_boards_proto_goTypes = nil
	file_base_v1_boards_proto_depIdxs = nil
}
