// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: base/v1/columns.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ColumnsService_CreateColumn_FullMethodName = "/taskboard.v1.ColumnsService/CreateColumn"
	ColumnsService_GetColumn_FullMethodName    = "/taskboard.v1.ColumnsService/GetColumn"
	ColumnsService_UpdateColumn_FullMethodName = "/taskboard.v1.ColumnsService/UpdateColumn"
	ColumnsService_DeleteColumn_FullMethodName = "/taskboard.v1.ColumnsService/DeleteColumn"
)

// ColumnsServiceClient is the client API for ColumnsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ColumnsServiceClient interface {
	CreateColumn(ctx context.Context, in *CreateColumnRequest, opts ...grpc.CallOption) (*CreateColumnResponse, error)
	GetColumn(ctx context.Context, in *GetColumnRequest, opts ...grpc.CallOption) (*GetColumnResponse, error)
	UpdateColumn(ctx context.Context, in *UpdateColumnRequest, opts ...grpc.CallOption) (*UpdateColumnResponse, error)
	DeleteColumn(ctx context.Context, in *DeleteColumnRequest, opts ...grpc.CallOption) (*DeleteColumnResponse, error)
}

type columnsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewColumnsServiceClient(cc grpc.ClientConnInterface) ColumnsServiceClient {
	return &columnsServiceClient{cc}
}

func (c *columnsServiceClient) CreateColumn(ctx context.Context, in *CreateColumnRequest, opts ...grpc.CallOption) (*CreateColumnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateColumnResponse)
	err := c.cc.Invoke(ctx, ColumnsService_CreateColumn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *columnsServiceClient) GetColumn(ctx context.Context, in *GetColumnRequest, opts ...grpc.CallOption) (*GetColumnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetColumnResponse)
	err := c.cc.Invoke(ctx, ColumnsService_GetColumn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *columnsServiceClient) UpdateColumn(ctx context.Context, in *UpdateColumnRequest, opts ...grpc.CallOption) (*UpdateColumnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateColumnResponse)
	err := c.cc.Invoke(ctx, ColumnsService_UpdateColumn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *columnsServiceClient) DeleteColumn(ctx context.Context, in *DeleteColumnRequest, opts ...grpc.CallOption) (*DeleteColumnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteColumnResponse)
	err := c.cc.Invoke(ctx, ColumnsService_DeleteColumn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ColumnsServiceServer is the server API for ColumnsService service.
// All implementations must embed UnimplementedColumnsServiceServer
// for forward compatibility.
type ColumnsServiceServer interface {
	CreateColumn(context.Context, *CreateColumnRequest) (*CreateColumnResponse, error)
	GetColumn(context.Context, *GetColumnRequest) (*GetColumnResponse, error)
	UpdateColumn(context.Context, *UpdateColumnRequest) (*UpdateColumnResponse, error)
	DeleteColumn(context.Context, *DeleteColumnRequest) (*DeleteColumnResponse, error)
	mustEmbedUnimplementedColumnsServiceServer()
}

// UnimplementedColumnsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedColumnsServiceServer struct{}

func (UnimplementedColumnsServiceServer) CreateColumn(context.Context, *CreateColumnRequest) (*CreateColumnResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateColumn not implemented")
}
func (UnimplementedColumnsServiceServer) GetColumn(context.Context, *GetColumnRequest) (*GetColumnResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetColumn not implemented")
}
func (UnimplementedColumnsServiceServer) UpdateColumn(context.Context, *UpdateColumnRequest) (*UpdateColumnResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateColumn not implemented")
}
func (UnimplementedColumnsServiceServer) DeleteColumn(context.Context, *DeleteColumnRequest) (*DeleteColumnResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteColumn not implemented")
}
func (UnimplementedColumnsServiceServer) mustEmbedUnimplementedColumnsServiceServer() {}
func (UnimplementedColumnsServiceServer) testEmbeddedByValue()                        {}

// UnsafeColumnsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ColumnsServiceServer will
// result in compilation errors.
type UnsafeColumnsServiceServer interface {
	mustEmbedUnimplementedColumnsServiceServer()
}

func RegisterColumnsServiceServer(s grpc.ServiceRegistrar, srv ColumnsServiceServer) {
	// If the following call panics, it indicates UnimplementedColumnsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ColumnsService_ServiceDesc, srv)
}

func _ColumnsService_CreateColumn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateColumnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColumnsServiceServer).CreateColumn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ColumnsService_CreateColumn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColumnsServiceServer).CreateColumn(ctx, req.(*CreateColumnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ColumnsService_GetColumn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetColumnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColumnsServiceServer).GetColumn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ColumnsService_GetColumn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColumnsServiceServer).GetColumn(ctx, req.(*GetColumnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ColumnsService_UpdateColumn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateColumnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColumnsServiceServer).UpdateColumn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ColumnsService_UpdateColumn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColumnsServiceServer).UpdateColumn(ctx, req.(*UpdateColumnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ColumnsService_DeleteColumn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteColumnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColumnsServiceServer).DeleteColumn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ColumnsService_DeleteColumn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColumnsServiceServer).DeleteColumn(ctx, req.(*DeleteColumnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ColumnsService_ServiceDesc is the grpc.ServiceDesc for ColumnsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ColumnsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "taskboard.v1.ColumnsService",
	HandlerType: (*ColumnsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateColumn",
			Handler:    _ColumnsService_CreateColumn_Handler,
		},
		{
			MethodName: "GetColumn",
			Handler:    _ColumnsService_GetColumn_Handler,
		},
		{
			MethodName: "UpdateColumn",
			Handler:    _ColumnsService_UpdateColumn_Handler,
		},
		{
			MethodName: "DeleteColumn",
			Handler:    _ColumnsService_DeleteColumn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "base/v1/columns.proto",
}
