// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: base/v1/columns.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Column struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BoardId       string                 `protobuf:"bytes,2,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	Position      int32                  `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Column) Reset() {
	*x = Column{}
	mi := &file_base_v1_columns_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Column) ProtoMessage() {}

func (x *Column) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_columns_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Column.ProtoReflect.Descriptor instead.
func (*Column) Descriptor() ([]byte, []int) {
	return file_base_v1_columns_proto_rawDescGZIP(), []int{0}
}

func (x *Column) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Column) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *Column) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type CreateColumnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseRequest           `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	BoardId       string                 `protobuf:"bytes,2,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	Position      int32                  `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateColumnRequest) Reset() {
	*x = CreateColumnRequest{}
	mi := &file_base_v1_columns_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateColumnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateColumnRequest) ProtoMessage() {}

func (x *CreateColumnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_columns_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateColumnRequest.ProtoReflect.Descriptor instead.
func (*CreateColumnRequest) Descriptor() ([]byte, []int) {
	return file_base_v1_columns_proto_rawDescGZIP(), []int{1}
}

func (x *CreateColumnRequest) GetBase() *BaseRequest {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *CreateColumnRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *CreateColumnRequest) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type CreateColumnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Column        *Column                `protobuf:"bytes,2,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateColumnResponse) Reset() {
	*x = CreateColumnResponse{}
	mi := &file_base_v1_columns_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateColumnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateColumnResponse) ProtoMessage() {}

func (x *CreateColumnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_columns_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateColumnResponse.ProtoReflect.Descriptor instead.
func (*CreateColumnResponse) Descriptor() ([]byte, []int) {
	return file_base_v1_columns_proto_rawDescGZIP(), []int{2}
}

func (x *CreateColumnResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *CreateColumnResponse) GetColumn() *Column {
	if x != nil {
		return x.Column
	}
	return nil
}

type GetColumnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseRequest           `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	ColumnId      string                 `protobuf:"bytes,2,opt,name=column_id,json=columnId,proto3" json:"column_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetColumnRequest) Reset() {
	*x = GetColumnRequest{}
	mi := &file_base_v1_columns_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetColumnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetColumnRequest) ProtoMessage() {}

func (x *GetColumnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_columns_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetColumnRequest.ProtoReflect.Descriptor instead.
func (*GetColumnRequest) Descriptor() ([]byte, []int) {
	return file_base_v1_columns_proto_rawDescGZIP(), []int{3}
}

func (x *GetColumnRequest) GetBase() *BaseRequest {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetColumnRequest) GetColumnId() string {
	if x != nil {
		return x.ColumnId
	}
	return ""
}

type GetColumnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Column        *Column                `protobuf:"bytes,2,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetColumnResponse) Reset() {
	*x = GetColumnResponse{}
	mi := &file_base_v1_columns_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetColumnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetColumnResponse) ProtoMessage() {}

func (x *GetColumnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_columns_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetColumnResponse.ProtoReflect.Descriptor instead.
func (*GetColumnResponse) Descriptor() ([]byte, []int) {
	return file_base_v1_columns_proto_rawDescGZIP(), []int{4}
}

func (x *GetColumnResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetColumnResponse) GetColumn() *Column {
	if x != nil {
		return x.Column
	}
	return nil
}

type MoveColumnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseRequest           `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	ColumnId      string                 `protobuf:"bytes,2,opt,name=column_id,json=columnId,proto3" json:"column_id,omitempty"`
	ToPosition    int32                  `protobuf:"varint,3,opt,name=to_position,json=toPosition,proto3" json:"to_position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveColumnRequest) Reset() {
	*x = MoveColumnRequest{}
	mi := &file_base_v1_columns_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveColumnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveColumnRequest) ProtoMessage() {}

func (x *MoveColumnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_columns_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveColumnRequest.ProtoReflect.Descriptor instead.
func (*MoveColumnRequest) Descriptor() ([]byte, []int) {
	return file_base_v1_columns_proto_rawDescGZIP(), []int{5}
}

func (x *MoveColumnRequest) GetBase() *BaseRequest {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *MoveColumnRequest) GetColumnId() string {
	if x != nil {
		return x.ColumnId
	}
	return ""
}

func (x *MoveColumnRequest) GetToPosition() int32 {
	if x != nil {
		return x.ToPosition
	}
	return 0
}

type MoveColumnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Column        *Column                `protobuf:"bytes,2,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveColumnResponse) Reset() {
	*x = MoveColumnResponse{}
	mi := &file_base_v1_columns_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveColumnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveColumnResponse) ProtoMessage() {}

func (x *MoveColumnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_columns_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveColumnResponse.ProtoReflect.Descriptor instead.
func (*MoveColumnResponse) Descriptor() ([]byte, []int) {
	return file_base_v1_columns_proto_rawDescGZIP(), []int{6}
}

func (x *MoveColumnResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *MoveColumnResponse) GetColumn() *Column {
	if x != nil {
		return x.Column
	}
	return nil
}

type DeleteColumnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseRequest           `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	ColumnId      string                 `protobuf:"bytes,2,opt,name=column_id,json=columnId,proto3" json:"column_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteColumnRequest) Reset() {
	*x = DeleteColumnRequest{}
	mi := &file_base_v1_columns_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteColumnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteColumnRequest) ProtoMessage() {}

func (x *DeleteColumnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_columns_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteColumnRequest.ProtoReflect.Descriptor instead.
func (*DeleteColumnRequest) Descriptor() ([]byte, []int) {
	return file_base_v1_columns_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteColumnRequest) GetBase() *BaseRequest {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *DeleteColumnRequest) GetColumnId() string {
	if x != nil {
		return x.ColumnId
	}
	return ""
}

type DeleteColumnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteColumnResponse) Reset() {
	*x = DeleteColumnResponse{}
	mi := &file_base_v1_columns_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteColumnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteColumnResponse) ProtoMessage() {}

func (x *DeleteColumnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_columns_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteColumnResponse.ProtoReflect.Descriptor instead.
func (*DeleteColumnResponse) Descriptor() ([]byte, []int) {
	return file_base_v1_columns_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteColumnResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

var File_base_v1_columns_proto protoreflect.FileDescriptor

const file_base_v1_columns_proto_rawDesc = "" +
	"\n" +
	"\x15base/v1/columns.proto\x12\ftaskboard.v1\x1a\x14base/v1/common.proto\"O\n" +
	"\x06Column\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bboard_id\x18\x02 \x01(\tR\aboardId\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\x05R\bposition\"{\n" +
	"\x13CreateColumnRequest\x12-\n" +
	"\x04base\x18\x01 \x01(\v2\x19.taskboard.v1.BaseRequestR\x04base\x12\x19\n" +
	"\bboard_id\x18\x02 \x01(\tR\aboardId\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\x05R\bposition\"t\n" +
	"\x14CreateColumnResponse\x12.\n" +
	"\x04base\x18\x01 \x01(\v2\x1a.taskboard.v1.BaseResponseR\x04base\x12,\n" +
	"\x06column\x18\x02 \x01(\v2\x14.taskboard.v1.ColumnR\x06column\"^\n" +
	"\x10GetColumnRequest\x12-\n" +
	"\x04base\x18\x01 \x01(\v2\x19.taskboard.v1.BaseRequestR\x04base\x12\x1b\n" +
	"\tcolumn_id\x18\x02 \x01(\tR\bcolumnId\"q\n" +
	"\x11GetColumnResponse\x12.\n" +
	"\x04base\x18\x01 \x01(\v2\x1a.taskboard.v1.BaseResponseR\x04base\x12,\n" +
	"\x06column\x18\x02 \x01(\v2\x14.taskboard.v1.ColumnR\x06column\"\x80\x01\n" +
	"\x11MoveColumnRequest\x12-\n" +
	"\x04base\x18\x01 \x01(\v2\x19.taskboard.v1.BaseRequestR\x04base\x12\x1b\n" +
	"\tcolumn_id\x18\x02 \x01(\tR\bcolumnId\x12\x1f\n" +
	"\vto_position\x18\x03 \x01(\x05R\n" +
	"toPosition\"r\n" +
	"\x12MoveColumnResponse\x12.\n" +
	"\x04base\x18\x01 \x01(\v2\x1a.taskboard.v1.BaseResponseR\x04base\x12,\n" +
	"\x06column\x18\x02 \x01(\v2\x14.taskboard.v1.ColumnR\x06column\"a\n" +
	"\x13DeleteColumnRequest\x12-\n" +
	"\x04base\x18\x01 \x01(\v2\x19.taskboard.v1.BaseRequestR\x04base\x12\x1b\n" +
	"\tcolumn_id\x18\x02 \x01(\tR\bcolumnId\"F\n" +
	"\x14DeleteColumnResponse\x12.\n" +
	"\x04base\x18\x01 \x01(\v2\x1a.taskboard.v1.BaseResponseR\x04base2\xdd\x02\n" +
	"\x0eColumnsService\x12U\n" +
	"\fCreateColumn\x12!.taskboard.v1.CreateColumnRequest\x1a\".taskboard.v1.CreateColumnResponse\x12L\n" +
	"\tGetColumn\x12\x1e.taskboard.v1.GetColumnRequest\x1a\x1f.taskboard.v1.GetColumnResponse\x12O\n" +
	"\n" +
	"MoveColumn\x12\x1f.taskboard.v1.MoveColumnRequest\x1a .taskboard.v1.MoveColumnResponse\x12U\n" +
	"\fDeleteColumn\x12!.taskboard.v1.DeleteColumnRequest\x1a\".taskboard.v1.DeleteColumnResponseB7Z5github.com/smarrog/task-board/shared/proto/base/v1;v1b\x06proto3"

var (
	file_base_v1_columns_proto_rawDescOnce sync.Once
	file_base_v1_columns_proto_rawDescData []byte
)

func file_base_v1_columns_proto_rawDescGZIP() []byte {
	file_base_v1_columns_proto_rawDescOnce.Do(func() {
		file_base_v1_columns_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_base_v1_columns_proto_rawDesc), len(file_base_v1_columns_proto_rawDesc)))
	})
	return file_base_v1_columns_proto_rawDescData
}

var file_base_v1_columns_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_base_v1_columns_proto_goTypes = []any{
	(*Column)(nil),               // 0: taskboard.v1.Column
	(*CreateColumnRequest)(nil),  // 1: taskboard.v1.CreateColumnRequest
	(*CreateColumnResponse)(nil), // 2: taskboard.v1.CreateColumnResponse
	(*GetColumnRequest)(nil),     // 3: taskboard.v1.GetColumnRequest
	(*GetColumnResponse)(nil),    // 4: taskboard.v1.GetColumnResponse
	(*MoveColumnRequest)(nil),    // 5: taskboard.v1.MoveColumnRequest
	(*MoveColumnResponse)(nil),   // 6: taskboard.v1.MoveColumnResponse
	(*DeleteColumnRequest)(nil),  // 7: taskboard.v1.DeleteColumnRequest
	(*DeleteColumnResponse)(nil), // 8: taskboard.v1.DeleteColumnResponse
	(*BaseRequest)(nil),          // 9: taskboard.v1.BaseRequest
	(*BaseResponse)(nil),         // 10: taskboard.v1.BaseResponse
}
var file_base_v1_columns_proto_depIdxs = []int32{
	9,  // 0: taskboard.v1.CreateColumnRequest.base:type_name -> taskboard.v1.BaseRequest
	10, // 1: taskboard.v1.CreateColumnResponse.base:type_name -> taskboard.v1.BaseResponse
	0,  // 2: taskboard.v1.CreateColumnResponse.column:type_name -> taskboard.v1.Column
	9,  // 3: taskboard.v1.GetColumnRequest.base:type_name -> taskboard.v1.BaseRequest
	10, // 4: taskboard.v1.GetColumnResponse.base:type_name -> taskboard.v1.BaseResponse
	0,  // 5: taskboard.v1.GetColumnResponse.column:type_name -> taskboard.v1.Column
	9,  // 6: taskboard.v1.MoveColumnRequest.base:type_name -> taskboard.v1.BaseRequest
	10, // 7: taskboard.v1.MoveColumnResponse.base:type_name -> taskboard.v1.BaseResponse
	0,  // 8: taskboard.v1.MoveColumnResponse.column:type_name -> taskboard.v1.Column
	9,  // 9: taskboard.v1.DeleteColumnRequest.base:type_name -> taskboard.v1.BaseRequest
	10, // 10: taskboard.v1.DeleteColumnResponse.base:type_name -> taskboard.v1.BaseResponse
	1,  // 11: taskboard.v1.ColumnsService.CreateColumn:input_type -> taskboard.v1.CreateColumnRequest
	3,  // 12: taskboard.v1.ColumnsService.GetColumn:input_type -> taskboard.v1.GetColumnRequest
	5,  // 13: taskboard.v1.ColumnsService.MoveColumn:input_type -> taskboard.v1.MoveColumnRequest
	7,  // 14: taskboard.v1.ColumnsService.DeleteColumn:input_type -> taskboard.v1.DeleteColumnRequest
	2,  // 15: taskboard.v1.ColumnsService.CreateColumn:output_type -> taskboard.v1.CreateColumnResponse
	4,  // 16: taskboard.v1.ColumnsService.GetColumn:output_type -> taskboard.v1.GetColumnResponse
	6,  // 17: taskboard.v1.ColumnsService.MoveColumn:output_type -> taskboard.v1.MoveColumnResponse
	8,  // 18: taskboard.v1.ColumnsService.DeleteColumn:output_type -> taskboard.v1.DeleteColumnResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_base_v1_columns_proto_init() }
func file_base_v1_columns_proto_init() {
	if File_base_v1_columns_proto != nil {
		return
	}
	file_base_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_base_v1_columns_proto_rawDesc), len(file_base_v1_columns_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_base_v1_columns_proto_goTypes,
		DependencyIndexes: file_base_v1_columns_proto_depIdxs,
		MessageInfos:      file_base_v1_columns_proto_msgTypes,
	}.Build()
	File_base_v1_columns_proto = out.File
	file_base_v1_columns_proto_goTypes = nil
	file_base_v1_columns_proto_depIdxs = nil
}
