// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: base/v1/common.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   string                 `protobuf:"bytes,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseRequest) Reset() {
	*x = BaseRequest{}
	mi := &file_base_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseRequest) ProtoMessage() {}

func (x *BaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseRequest.ProtoReflect.Descriptor instead.
func (*BaseRequest) Descriptor() ([]byte, []int) {
	return file_base_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *BaseRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

type BaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_base_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_base_v1_common_proto_rawDescGZIP(), []int{1}
}

var File_base_v1_common_proto protoreflect.FileDescriptor

const file_base_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x14base/v1/common.proto\x12\ftaskboard.v1\"0\n" +
	"\vBaseRequest\x12!\n" +
	"\frequester_id\x18\x01 \x01(\tR\vrequesterId\"\x0e\n" +
	"\fBaseResponseB2Z0github.com/smarrog/task-board/shared/proto/v1;v1b\x06proto3"

var (
	file_base_v1_common_proto_rawDescOnce sync.Once
	file_base_v1_common_proto_rawDescData []byte
)

func file_base_v1_common_proto_rawDescGZIP() []byte {
	file_base_v1_common_proto_rawDescOnce.Do(func() {
		file_base_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_base_v1_common_proto_rawDesc), len(file_base_v1_common_proto_rawDesc)))
	})
	return file_base_v1_common_proto_rawDescData
}

var file_base_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_base_v1_common_proto_goTypes = []any{
	(*BaseRequest)(nil),  // 0: taskboard.v1.BaseRequest
	(*BaseResponse)(nil), // 1: taskboard.v1.BaseResponse
}
var file_base_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_base_v1_common_proto_init() }
func file_base_v1_common_proto_init() {
	if File_base_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_base_v1_common_proto_rawDesc), len(file_base_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_base_v1_common_proto_goTypes,
		DependencyIndexes: file_base_v1_common_proto_depIdxs,
		MessageInfos:      file_base_v1_common_proto_msgTypes,
	}.Build()
	File_base_v1_common_proto = out.File
	file_base_v1_common_proto_goTypes = nil
	file_base_v1_common_proto_depIdxs = nil
}
