// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: v1/events.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	EventId    string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	OccurredAt int64                  `protobuf:"varint,2,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	UserId     int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Producer   string                 `protobuf:"bytes,4,opt,name=producer,proto3" json:"producer,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_TaskCreated
	//	*Event_TaskUpdated
	//	*Event_TaskMoved
	Payload       isEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetOccurredAt() int64 {
	if x != nil {
		return x.OccurredAt
	}
	return 0
}

func (x *Event) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Event) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetTaskCreated() *TaskCreated {
	if x != nil {
		if x, ok := x.Payload.(*Event_TaskCreated); ok {
			return x.TaskCreated
		}
	}
	return nil
}

func (x *Event) GetTaskUpdated() *TaskUpdated {
	if x != nil {
		if x, ok := x.Payload.(*Event_TaskUpdated); ok {
			return x.TaskUpdated
		}
	}
	return nil
}

func (x *Event) GetTaskMoved() *TaskMoved {
	if x != nil {
		if x, ok := x.Payload.(*Event_TaskMoved); ok {
			return x.TaskMoved
		}
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_TaskCreated struct {
	TaskCreated *TaskCreated `protobuf:"bytes,5,opt,name=task_created,json=taskCreated,proto3,oneof"`
}

type Event_TaskUpdated struct {
	TaskUpdated *TaskUpdated `protobuf:"bytes,6,opt,name=task_updated,json=taskUpdated,proto3,oneof"`
}

type Event_TaskMoved struct {
	TaskMoved *TaskMoved `protobuf:"bytes,7,opt,name=task_moved,json=taskMoved,proto3,oneof"`
}

func (*Event_TaskCreated) isEvent_Payload() {}

func (*Event_TaskUpdated) isEvent_Payload() {}

func (*Event_TaskMoved) isEvent_Payload() {}

type TaskSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ColumnId      int64                  `protobuf:"varint,2,opt,name=column_id,json=columnId,proto3" json:"column_id,omitempty"`
	BoardId       int64                  `protobuf:"varint,3,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	AssigneeId    int64                  `protobuf:"varint,6,opt,name=assignee_id,json=assigneeId,proto3" json:"assignee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskSnapshot) Reset() {
	*x = TaskSnapshot{}
	mi := &file_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSnapshot) ProtoMessage() {}

func (x *TaskSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSnapshot.ProtoReflect.Descriptor instead.
func (*TaskSnapshot) Descriptor() ([]byte, []int) {
	return file_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *TaskSnapshot) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskSnapshot) GetColumnId() int64 {
	if x != nil {
		return x.ColumnId
	}
	return 0
}

func (x *TaskSnapshot) GetBoardId() int64 {
	if x != nil {
		return x.BoardId
	}
	return 0
}

func (x *TaskSnapshot) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TaskSnapshot) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TaskSnapshot) GetAssigneeId() int64 {
	if x != nil {
		return x.AssigneeId
	}
	return 0
}

type TaskCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *TaskSnapshot          `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCreated) Reset() {
	*x = TaskCreated{}
	mi := &file_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCreated) ProtoMessage() {}

func (x *TaskCreated) ProtoReflect() protoreflect.Message {
	mi := &file_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCreated.ProtoReflect.Descriptor instead.
func (*TaskCreated) Descriptor() ([]byte, []int) {
	return file_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *TaskCreated) GetSnapshot() *TaskSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type TaskUpdated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *TaskSnapshot          `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskUpdated) Reset() {
	*x = TaskUpdated{}
	mi := &file_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskUpdated) ProtoMessage() {}

func (x *TaskUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskUpdated.ProtoReflect.Descriptor instead.
func (*TaskUpdated) Descriptor() ([]byte, []int) {
	return file_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *TaskUpdated) GetSnapshot() *TaskSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type TaskMoved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *TaskSnapshot          `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	ToColumnId    int64                  `protobuf:"varint,2,opt,name=to_column_id,json=toColumnId,proto3" json:"to_column_id,omitempty"`
	ToBoardId     int64                  `protobuf:"varint,3,opt,name=to_board_id,json=toBoardId,proto3" json:"to_board_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskMoved) Reset() {
	*x = TaskMoved{}
	mi := &file_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskMoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskMoved) ProtoMessage() {}

func (x *TaskMoved) ProtoReflect() protoreflect.Message {
	mi := &file_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskMoved.ProtoReflect.Descriptor instead.
func (*TaskMoved) Descriptor() ([]byte, []int) {
	return file_v1_events_proto_rawDescGZIP(), []int{4}
}

func (x *TaskMoved) GetSnapshot() *TaskSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *TaskMoved) GetToColumnId() int64 {
	if x != nil {
		return x.ToColumnId
	}
	return 0
}

func (x *TaskMoved) GetToBoardId() int64 {
	if x != nil {
		return x.ToBoardId
	}
	return 0
}

var File_v1_events_proto protoreflect.FileDescriptor

const file_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/events.proto\x12\tevents.v1\"\xb4\x02\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1f\n" +
	"\voccurred_at\x18\x02 \x01(\x03R\n" +
	"occurredAt\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bproducer\x18\x04 \x01(\tR\bproducer\x12;\n" +
	"\ftask_created\x18\x05 \x01(\v2\x16.events.v1.TaskCreatedH\x00R\vtaskCreated\x12;\n" +
	"\ftask_updated\x18\x06 \x01(\v2\x16.events.v1.TaskUpdatedH\x00R\vtaskUpdated\x125\n" +
	"\n" +
	"task_moved\x18\a \x01(\v2\x14.events.v1.TaskMovedH\x00R\ttaskMovedB\t\n" +
	"\apayload\"\xb8\x01\n" +
	"\fTaskSnapshot\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x1b\n" +
	"\tcolumn_id\x18\x02 \x01(\x03R\bcolumnId\x12\x19\n" +
	"\bboard_id\x18\x03 \x01(\x03R\aboardId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1f\n" +
	"\vassignee_id\x18\x06 \x01(\x03R\n" +
	"assigneeId\"B\n" +
	"\vTaskCreated\x123\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x17.events.v1.TaskSnapshotR\bsnapshot\"B\n" +
	"\vTaskUpdated\x123\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x17.events.v1.TaskSnapshotR\bsnapshot\"\x82\x01\n" +
	"\tTaskMoved\x123\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x17.events.v1.TaskSnapshotR\bsnapshot\x12 \n" +
	"\fto_column_id\x18\x02 \x01(\x03R\n" +
	"toColumnId\x12\x1e\n" +
	"\vto_board_id\x18\x03 \x01(\x03R\ttoBoardIdB'Z%github.com/smarrog/task-board/shared/proto/v1;v1b\x06proto3"

var (
	file_v1_events_proto_rawDescOnce sync.Once
	file_v1_events_proto_rawDescData []byte
)

func file_v1_events_proto_rawDescGZIP() []byte {
	file_v1_events_proto_rawDescOnce.Do(func() {
		file_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_events_proto_rawDesc), len(file_v1_events_proto_rawDesc)))
	})
	return file_v1_events_proto_rawDescData
}

var file_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_v1_events_proto_goTypes = []any{
	(*Event)(nil),        // 0: events.v1.Event
	(*TaskSnapshot)(nil), // 1: events.v1.TaskSnapshot
	(*TaskCreated)(nil),  // 2: events.v1.TaskCreated
	(*TaskUpdated)(nil),  // 3: events.v1.TaskUpdated
	(*TaskMoved)(nil),    // 4: events.v1.TaskMoved
}
var file_v1_events_proto_depIdxs = []int32{
	2, // 0: events.v1.Event.task_created:type_name -> events.v1.TaskCreated
	3, // 1: events.v1.Event.task_updated:type_name -> events.v1.TaskUpdated
	4, // 2: events.v1.Event.task_moved:type_name -> events.v1.TaskMoved
	1, // 3: events.v1.TaskCreated.snapshot:type_name -> events.v1.TaskSnapshot
	1, // 4: events.v1.TaskUpdated.snapshot:type_name -> events.v1.TaskSnapshot
	1, // 5: events.v1.TaskMoved.snapshot:type_name -> events.v1.TaskSnapshot
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_v1_events_proto_init() }
func file_v1_events_proto_init() {
	if File_v1_events_proto != nil {
		return
	}
	file_v1_events_proto_msgTypes[0].OneofWrappers = []any{
		(*Event_TaskCreated)(nil),
		(*Event_TaskUpdated)(nil),
		(*Event_TaskMoved)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_events_proto_rawDesc), len(file_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_events_proto_goTypes,
		DependencyIndexes: file_v1_events_proto_depIdxs,
		MessageInfos:      file_v1_events_proto_msgTypes,
	}.Build()
	File_v1_events_proto = out.File
	file_v1_events_proto_goTypes = nil
	file_v1_events_proto_depIdxs = nil
}
